# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "People"
  weight = 2

[[main]]
  name = "Coordination board"
  parent = "People"
  url = "people/coordination-board"
  weight = 1

[[main]]
  name = "Executive board"
  parent = "People"
  url = "people/executive-board"
  weight = 2

[[main]]
  name = "Advisory board"
  parent = "People"
  url = "people/advisory-board"
  weight = 3

[[main]]
  name = "Software"
  weight = 3

[[main]]
  name = "The NEMO ocean model"
  parent = "Software"
  url = "https://www.nemo-ocean.eu"
  weight = 1

[[main]]
  name = "Sharing NEMO experiments"
  parent = "Software"
  url = "https://immerse-ocean.eu/nemo-simsar/"
  weight = 2

[[main]]
  name = "Analysing error covariances"
  parent = "Software"
  url = "https://github.com/MetOffice/ocean_error_covs"
  weight = 3 


[[main]]
  name = "Demonstrators"
  weight = 4

[[main]]
  name = "NEMO idealized test cases"
  parent = "Demonstrators"
  url = "https://github.com/NEMO-ocean/NEMO-examples"
  weight = 1

[[main]]
  name = "Prototype models for CMEMS"
  parent = "Demonstrators"
  url = "prototypes"
  weight = 2

[[main]]
  name = "Downstream use cases"
  parent = "Demonstrators"
  url = "downstream-use-cases"
  weight = 3

[[main]]
  name = "Dissemination"
  weight = 5

[[main]]
  name = "Publications"
  parent = "Dissemination"
  url = "publications"
  weight = 1

[[main]]
  name = "Deliverables"
  parent = "Dissemination"
  url = "deliverables"
  weight = 2

[[main]]
  name = "Join us"
  weight = 6

[[main]]
  name = "NEMO repository"
  parent = "Join us"
  url = "http://forge.ipsl.jussieu.fr/nemo/wiki/Users"
  weight = 1

[[main]]
  name = "NEMO users forum"
  parent = "Join us"
  url = "http://nemo-ocean.discourse.group"
  weight = 2

[[main]]
  name = "Mattermost server"
  parent = "Join us"
  url = "https://chat.immerse-ocean.eu/login "
  weight = 3

[[main]]
  name = "News"
  url = "#posts"
  weight = 7
